service: bookListNotionPage

frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby2.7
  memorySize: 128
  region: ap-northeast-1
  stage: dev
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'ssm:GetParameters'
          Resource:
            - !Join ['', ['arn:', !Ref AWS::Partition, ':ssm:', !Ref AWS::Region, ':', !Ref AWS::AccountId, ':parameter/line_notion_database_id']]
            - !Join ['', ['arn:', !Ref AWS::Partition, ':ssm:', !Ref AWS::Region, ':', !Ref AWS::AccountId, ':parameter/line_notion_integration_token']]

plugins:
  - serverless-prune-plugin
  - serverless-ruby-layer

package:
  individually: true
  patterns:
    - '!./**'

custom:
  prune:
    automatic: true
    number: 3
    includeLayers: true
  rubyLayer:
    include_functions:
      - createNotionBookListPage

functions:
  createNotionBookListPage:
    handler: functions/create_notion_book_list_page/main.handler
    description: create new page to notion book list database
    package:
      patterns:
        - 'functions/create_notion_book_list_page/**'
    events:
      - httpApi:
          path: /create_page
          method: POST
