service: booklist_line_notion

frameworkVersion: '3'

provider:
  name: aws
  runtime: ruby2.7
  memorySize: 128
  region: ap-northeast-1
  stage: dev

plugins:
  - serverless-prune-plugin
  - serverless-ruby-layer

package:
  patterns:
    - '!./**'
    - 'functions/**'

custom:
  prune:
    automatic: true
    number: 3
    includeLayers: true
  rubyLayer:
    include_functions:
      - createNotionBookListPage

functions:
  hello:
    handler: functions/hello_world.handler
    description: Simple Hello, World
  createNotionBookListPage:
    handler: functions/create_notion_book_list_page/main.handler
    description: create new page to notion book list database
